import {Product, Coupon, Address, CartItem} from '../types';
import images from '../asset';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    brand: 'Tata Tea',
    name: 'Gold Premium Assam Tea Rich Taste & Irresistible',
    weight: '1kg',
    price: 444,
    originalPrice: 444,
    discount: 52,
    image: images.tea,
    images: [images.tea, images.tea, images.tea],
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
    options: [
      {id: 'o1', label: '3X1kg', price: 444, originalPrice: 444, stock: 10},
      {id: 'o2', label: '1kg', price: 199, originalPrice: 199, stock: 5},
    ],
  },
  {
    id: '2',
    brand: 'Cadbury',
    name: 'Dairy milk Silk Chocolate Bar Dairy milk Silk Chocolate Bar',
    weight: '64 g',
    price: 444,
    originalPrice: 444,
    discount: 52,
    image: images.chocolateSmall,
    images: [images.chocolateLarge, images.chocolateLarge, images.chocolateLarge, images.chocolateLarge],
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    options: [
      {id: 'o1', label: '64g', price: 444, originalPrice: 444, stock: 8},
      {id: 'o2', label: '128g', price: 799, originalPrice: 799, stock: 3},
    ],
  },
  {
    id: '3',
    brand: 'Tata Tea',
    name: 'Gold Premium Assam Tea Rich Taste & Irresistible',
    weight: '1kg',
    price: 444,
    originalPrice: 444,
    discount: 52,
    image: images.tea,
    images: [images.tea, images.tea],
    description: 'Premium Assam tea with rich taste and irresistible aroma.',
    options: [
      {id: 'o1', label: '3X1kg', price: 444, originalPrice: 444, stock: 0},
      {id: 'o2', label: '1kg', price: 199, originalPrice: 199, stock: 2},
    ],
  },
  {
    id: '4',
    brand: 'Organic',
    name: 'Organic apple',
    weight: '1kg',
    price: 199,
    originalPrice: 299,
    discount: 33,
    image: images.apple,
    images: [images.apple],
    description: 'Fresh organic apples sourced directly from Himalayan farms.',
    options: [
      {id: 'o1', label: '1kg', price: 199, originalPrice: 299, stock: 15},
    ],
  },
];

export const MOCK_COUPONS: Coupon[] = [
  {
    id: 'c1',
    code: 'ABCDEFGHI',
    discount: 250,
    discountType: 'flat',
    minOrder: 500,
    description: 'Upto ₹120 on orders above ₹1200',
    isApplied: false,
  },
  {
    id: 'c2',
    code: 'ABCDEFGHI',
    discount: 6,
    discountType: 'percent',
    minOrder: 300,
    description: 'Upto ₹120 on orders above ₹1200',
    isApplied: false,
  },
  {
    id: 'c3',
    code: 'ABCDEFGHI',
    discount: 6,
    discountType: 'percent',
    minOrder: 200,
    description: 'Upto ₹120 on orders above ₹1200',
    isApplied: false,
  },
];

export const MOCK_ADDRESSES: Address[] = [
  {
    id: 'a1',
    label: 'Home',
    fullAddress: 'Flat No. 301, XYZ Apartments, ABC Road, Mumbai - 400001',
    pincode: '400001',
    isServiceable: true,
    deliveryTime: '30-40 mins',
  },
  {
    id: 'a2',
    label: 'Office',
    fullAddress: 'Office No. 5, Business Park, MG Road, Bangalore - 560001',
    pincode: '560001',
    isServiceable: false,
    deliveryTime: undefined,
  },
];

export const INITIAL_CART_ITEMS: CartItem[] = [
  {
    id: 'ci1',
    productId: '1',
    name: 'Gold Premium Assam Tea Rich Taste & Irresistible',
    brand: 'Tata Tea',
    weight: '1kg',
    price: 199,
    originalPrice: 199,
    image: images.tea,
    quantity: 1,
    optionId: 'o2',
    optionLabel: '1kg',
    isOutOfStock: false,
  },
  {
    id: 'ci2',
    productId: '1',
    name: 'Gold Premium Assam Tea Rich Taste & Irresistible',
    brand: 'Tata Tea',
    weight: '3kg',
    price: 444,
    originalPrice: 444,
    image: images.tea,
    quantity: 1,
    optionId: 'o1',
    optionLabel: '3X1kg',
    isOutOfStock: false,
  },
  {
    id: 'ci3',
    productId: '3',
    name: 'Gold Premium Assam Tea Rich Taste & Irresistible',
    brand: 'Tata Tea',
    weight: '1kg',
    price: 199,
    originalPrice: 199,
    image: images.tea,
    quantity: 1,
    optionId: 'o2',
    optionLabel: '1kg',
    isOutOfStock: false,
  },
  {
    id: 'ci4',
    productId: '1',
    name: 'Gold Premium Assam Tea Rich Taste & Irresistible',
    brand: 'Tata Tea',
    weight: '3kg',
    price: 444,
    originalPrice: 444,
    image: images.tea,
    quantity: 1,
    optionId: 'o1',
    optionLabel: '3X1kg',
    isOutOfStock: true,
  },
];
